# Generated by Django 5.2.11 on 2026-02-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_notes', models.TextField(verbose_name='یادداشت پزشک')),
                ('prescription', models.TextField(blank=True, null=True, verbose_name='نسخه')),
                ('weight', models.FloatField(verbose_name='وزن (کیلوگرم)')),
                ('height', models.FloatField(verbose_name='قد (سانتی\u200cمتر)')),
                ('bmi', models.FloatField(blank=True, null=True, verbose_name='شاخص توده بدنی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'رکورد پزشکی',
                'verbose_name_plural': 'رکوردهای پزشکی',
                'ordering': ['-created_at'],
            },
        ),
    ]
