# Generated by Django 5.2.11 on 2026-02-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_notes', models.TextField(verbose_name='یادداشت پزشک')),
                ('prescription', models.TextField(blank=True, null=True, verbose_name='نسخه')),
                ('weight', models.FloatField(verbose_name='وزن (کیلوگرم)')),
                ('height', models.FloatField(verbose_name='قد (سانتی\u200cمتر)')),
                ('bmi', models.FloatField(blank=True, null=True, verbose_name='شاخص توده بدنی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
