# Generated by Django 5.2.11 on 2026-02-07 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='chief_complaint',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='physical_examination',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='doctor_notes',
            field=models.TextField(default='...', verbose_name='یادداشت پزشک'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='bmi',
            field=models.FloatField(blank=True, null=True, verbose_name='شاخص توده بدنی'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='height',
            field=models.FloatField(verbose_name='قد (سانتی\u200cمتر)'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='prescription',
            field=models.TextField(blank=True, null=True, verbose_name='نسخه'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='weight',
            field=models.FloatField(verbose_name='وزن (کیلوگرم)'),
        ),
    ]
