# Generated by Django 5.2.11 on 2026-02-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100, verbose_name='نام پزشک')),
                ('specialty', models.CharField(max_length=100, verbose_name='تخصص')),
                ('biography', models.TextField(verbose_name='بیوگرافی')),
                ('education', models.TextField(verbose_name='تحصیلات')),
                ('experience', models.TextField(verbose_name='تجربیات')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='doctor/', verbose_name='عکس پروفایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'پروفایل پزشک',
                'verbose_name_plural': 'پروفایل\u200cهای پزشکان',
            },
        ),
        migrations.CreateModel(
            name='OfficeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(default='نام پزشک', max_length=100, verbose_name='نام پزشک')),
                ('specialty', models.CharField(blank=True, max_length=100, verbose_name='تخصص')),
                ('biography', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('address', models.TextField(blank=True, verbose_name='آدرس مطب')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='شماره تلفن')),
                ('default_interval', models.IntegerField(default=30, verbose_name='فاصله پیش\u200cفرض نوبت\u200cها (دقیقه)')),
                ('default_appointment_price', models.IntegerField(default=0, verbose_name='قیمت پیش\u200cفرض نوبت (تومان)')),
                ('send_sms_on_book', models.BooleanField(default=True, verbose_name='پیامک هنگام رزرو')),
                ('send_sms_reminder', models.BooleanField(default=True, verbose_name='پیامک یادآوری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات مطب',
                'verbose_name_plural': 'تنظیمات مطب',
            },
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], unique=True, verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'ساعات کاری',
                'verbose_name_plural': 'ساعات کاری',
                'ordering': ['day'],
            },
        ),
    ]
