# Generated by Django 5.2.11 on 2026-02-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officesettings',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='officesettings',
            name='sms_notification',
        ),
        migrations.RemoveField(
            model_name='officesettings',
            name='sms_reminder',
        ),
        migrations.AddField(
            model_name='officesettings',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='officesettings',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='officesettings',
            name='send_sms_on_book',
            field=models.BooleanField(default=True, verbose_name='پیامک هنگام رزرو'),
        ),
        migrations.AddField(
            model_name='officesettings',
            name='send_sms_reminder',
            field=models.BooleanField(default=True, verbose_name='پیامک یادآوری'),
        ),
        migrations.AlterField(
            model_name='officesettings',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='officesettings',
            name='doctor_name',
            field=models.CharField(default='نام پزشک', max_length=100),
        ),
        migrations.AlterField(
            model_name='officesettings',
            name='specialty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='day',
            field=models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], unique=True),
        ),
    ]
