# Generated by Django 5.2.11 on 2026-02-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('question_text', models.TextField(verbose_name='متن سوال')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='پاسخ پزشک')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پاسخ'), ('answered', 'پاسخ داده شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ')),
            ],
            options={
                'verbose_name': 'مشاوره',
                'verbose_name_plural': 'مشاوره\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
