# Generated by Django 5.2.11 on 2026-02-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='consultation_files/', verbose_name='فایل ضمیمه')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('question_text', models.TextField(verbose_name='متن سوال')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='پاسخ پزشک')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پاسخ'), ('answered', 'پاسخ داده شده')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
