# Generated by Django 5.2.11 on 2026-02-07 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='file',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='is_answered',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='question',
        ),
        migrations.AddField(
            model_name='consultation',
            name='answer_text',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ پزشک'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='question_text',
            field=models.TextField(default='.', verbose_name='متن سوال'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پاسخ'), ('answered', 'پاسخ داده شده')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='consultation',
            name='subject',
            field=models.CharField(default='...', max_length=200, verbose_name='موضوع'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
