# Generated by Django 5.2.11 on 2026-02-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_remove_consultation_answer_remove_consultation_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='consultation_files/', verbose_name='فایل ضمیمه'),
        ),
    ]
