# Generated by Django 5.2.11 on 2026-02-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('site', 'سایت'), ('manual', 'دستی'), ('scraper', 'خارجی')], default='site', max_length=10)),
                ('status', models.CharField(choices=[('reserved', 'رزرو'), ('waiting', 'اتاق انتظار'), ('completed', 'پایان ویزیت')], default='reserved', max_length=15)),
                ('booking_type', models.CharField(choices=[('in_person', 'حضوری'), ('phone', 'تلفنی')], default='in_person', max_length=10)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
    ]
