# Generated by Django 5.2.11 on 2026-02-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('site', 'سایت'), ('manual', 'دستی'), ('phone', 'تلفنی')], default='site', max_length=10, verbose_name='منبع')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('arrived', 'رسیده'), ('canceled', 'لغو'), ('completed', 'تکمیل شده'), ('no-show', 'عدم حضور')], default='pending', max_length=15, verbose_name='وضعیت')),
                ('booking_type', models.CharField(choices=[('in_person', 'حضوری'), ('phone', 'تلفنی')], default='in_person', max_length=20, verbose_name='نوع ویزیت')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت (تومان)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('visit_reason', models.TextField(blank=True, null=True, verbose_name='علت مراجعه')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای پزشک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'نوبت ویزیت',
                'verbose_name_plural': 'نوبت\u200cهای ویزیت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ (میلادی)')),
                ('jalali_date_cached', models.CharField(blank=True, help_text='مثال: 1403/10/16', max_length=10, null=True, verbose_name='تاریخ شمسی (کش)')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='بسته شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'اسلات زمانی',
                'verbose_name_plural': 'اسلات\u200cهای زمانی',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
