# Generated by Django 5.2.11 on 2026-02-07 11:38

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_reason', models.TextField(blank=True, null=True, verbose_name='علت مراجعه')),
                ('source', models.CharField(choices=[('site', 'سایت'), ('manual', 'دستی'), ('scraper', 'خارجی')], default='site', max_length=10, verbose_name='منبع نوبت')),
                ('status', models.CharField(choices=[('reserved', 'رزرو'), ('waiting', 'اتاق انتظار'), ('completed', 'پایان ویزیت')], default='reserved', max_length=15, verbose_name='وضعیت')),
                ('booking_type', models.CharField(choices=[('in_person', 'حضوری'), ('phone', 'تلفنی')], default='in_person', max_length=10, verbose_name='نوع نوبت')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ شمسی')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='بسته شده')),
            ],
            options={
                'verbose_name': 'زمان حضور',
                'verbose_name_plural': 'زمان\u200cهای حضور',
            },
        ),
    ]
