# Generated by Django 5.2.11 on 2026-02-07 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='appointments.timeslot'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='بسته شده'),
        ),
    ]
