# Generated by Django 5.2.11 on 2026-02-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_slot_alter_timeslot_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visit_reason',
            field=models.TextField(blank=True, null=True, verbose_name='علت مراجعه'),
        ),
    ]
