# Generated by Django 5.2.11 on 2026-02-07 11:24

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_visit_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'نوبت', 'verbose_name_plural': 'نوبت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'زمان حضور', 'verbose_name_plural': 'زمان\u200cهای حضور'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booking_type',
            field=models.CharField(choices=[('in_person', 'حضوری'), ('phone', 'تلفنی')], default='in_person', max_length=10, verbose_name='نوع نوبت'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='بیمار'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='appointments.timeslot', verbose_name='زمان نوبت'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='source',
            field=models.CharField(choices=[('site', 'سایت'), ('manual', 'دستی'), ('scraper', 'خارجی')], default='site', max_length=10, verbose_name='منبع نوبت'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('reserved', 'رزرو'), ('waiting', 'اتاق انتظار'), ('completed', 'پایان ویزیت')], default='reserved', max_length=15, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ شمسی'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(verbose_name='ساعت شروع'),
        ),
    ]
